apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
		component: neo4j
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80